device: "cuda"
imsize: 64 # useless for testing
batch_size : 1 
psnr_reward : True
threshold_psnr: -25
threshold_rmse: -0.01
sliders_to_use : ["contrast","exposure","shadows","highlights","whites"]

features_size : 512 #useless